/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dto.Auth;
import dto.UserType;
import static gui.Login.auth;
import javax.swing.JOptionPane;

/**
 *
 * @author vidur
 */
public class DashboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public DashboardFrame() {
        initComponents();
        lbl_frameTitle.setText(Login.auth.getAuthType().name()+" PANEL");
        lb_adminGreeting.setText("Hello, "+Login.auth.getEmployee().getFirstName()+" !");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel2 = new components.RoundedPanel();
        lbl_frameTitle = new javax.swing.JLabel();
        roundedPanel1 = new components.RoundedPanel();
        lb_adminGreeting = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        sellProductPanel1 = new gui.SellProductPanel();
        productsPanel1 = new gui.ProductsPanel();
        purchuseOrderPanel1 = new gui.PurchuseOrderPanel();
        stocksPanel1 = new gui.StocksPanel();
        suppliersPanel1 = new gui.SuppliersPanel();
        gRNPanel1 = new gui.GRNPanel();
        customerPanel1 = new gui.CustomerPanel();
        invoicePanel1 = new gui.InvoicePanel();
        userPanel1 = new gui.UserPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        roundedPanel2.setBackground(new java.awt.Color(221, 231, 244));
        roundedPanel2.setLayout(new java.awt.FlowLayout());

        lbl_frameTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_frameTitle.setText("ADMIN PANEL");
        roundedPanel2.add(lbl_frameTitle);

        roundedPanel1.setBackground(new java.awt.Color(0, 122, 255));

        lb_adminGreeting.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_adminGreeting.setForeground(new java.awt.Color(255, 255, 255));
        lb_adminGreeting.setText("Hello Vidura !");
        lb_adminGreeting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_adminGreetingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(lb_adminGreeting, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_adminGreeting)
                .addContainerGap())
        );

        roundedPanel2.add(roundedPanel1);

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane2.addTab("", new javax.swing.ImageIcon(getClass().getResource("/assets/Sell.png")), sellProductPanel1); // NOI18N
        jTabbedPane2.addTab("", new javax.swing.ImageIcon(getClass().getResource("/assets/Product.png")), productsPanel1); // NOI18N
        jTabbedPane2.addTab("", new javax.swing.ImageIcon(getClass().getResource("/assets/Truck.png")), purchuseOrderPanel1); // NOI18N
        jTabbedPane2.addTab("", new javax.swing.ImageIcon(getClass().getResource("/assets/Sell Stock.png")), stocksPanel1); // NOI18N
        jTabbedPane2.addTab("", new javax.swing.ImageIcon(getClass().getResource("/assets/Supplier.png")), suppliersPanel1); // NOI18N
        jTabbedPane2.addTab("", new javax.swing.ImageIcon(getClass().getResource("/assets/Bullet List.png")), gRNPanel1); // NOI18N
        jTabbedPane2.addTab("", new javax.swing.ImageIcon(getClass().getResource("/assets/Budget2.png")), customerPanel1); // NOI18N
        jTabbedPane2.addTab("", new javax.swing.ImageIcon(getClass().getResource("/assets/Invoice.png")), invoicePanel1); // NOI18N
        jTabbedPane2.addTab("", new javax.swing.ImageIcon(getClass().getResource("/assets/Users.png")), userPanel1); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(roundedPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addGap(91, 91, 91))
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 821, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, Short.MAX_VALUE))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lb_adminGreetingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_adminGreetingMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(
                null,
                "Are you sure that you want to logout?",
                "Logout Confirmation",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );
        if (response == JOptionPane.YES_OPTION) {
            System.out.println("logout.");
            this.dispose();
            Login.auth = null;
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_lb_adminGreetingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
         Login.auth = new Auth("admin", "123", UserType.ADMIN);
         try{
         auth.isAuthenticated();
         }catch(Exception ex){
             
         }
         com.formdev.flatlaf.themes.FlatMacLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.CustomerPanel customerPanel1;
    private gui.GRNPanel gRNPanel1;
    private gui.InvoicePanel invoicePanel1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lb_adminGreeting;
    private javax.swing.JLabel lbl_frameTitle;
    private gui.ProductsPanel productsPanel1;
    private gui.PurchuseOrderPanel purchuseOrderPanel1;
    private components.RoundedPanel roundedPanel1;
    private components.RoundedPanel roundedPanel2;
    private gui.SellProductPanel sellProductPanel1;
    private gui.StocksPanel stocksPanel1;
    private gui.SuppliersPanel suppliersPanel1;
    private gui.UserPanel userPanel1;
    // End of variables declaration//GEN-END:variables
}
