/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.raven.chart.ModelChart;
import java.awt.Color;
import java.util.Random;

/**
 *
 * @author vidur
 */
public class OverviewPanel extends javax.swing.JPanel {

    /**
     * Creates new form OverviewPanel
     */
    public OverviewPanel() {
        initComponents();
        initData();
        randomize();
    }
    
    private void randomize() {
        Random random = new Random();
        
        // Define the range for the random values
        int minValue = 50;
        int maxValue = 100;

        chart.addLegend("Income", new Color(245, 189, 135));
        chart.addLegend("Expense", new Color(135, 189, 245));
        chart.addLegend("Profit", new Color(189, 135, 245));
        chart.addLegend("Cost", new Color(139, 229, 222));

        chart.addData(new ModelChart("January", generateRandomArray(random, minValue, maxValue)));
        chart.addData(new ModelChart("February", generateRandomArray(random, minValue, maxValue)));
        chart.addData(new ModelChart("March", generateRandomArray(random, minValue, maxValue)));
        chart.addData(new ModelChart("April", generateRandomArray(random, minValue, maxValue)));
        chart.addData(new ModelChart("May", generateRandomArray(random, minValue, maxValue)));
        chart.addData(new ModelChart("June", generateRandomArray(random, minValue, maxValue)));
    }
    
     private double[] generateRandomArray(Random random, int minValue, int maxValue) {
         System.out.println("WORKING");
        double[] randomValues = new double[4];
        for (int i = 0; i < randomValues.length; i++) {
            randomValues[i] = minValue + (maxValue - minValue) * random.nextDouble();
        }
        return randomValues;
    }
    
    
    private void initData(){
        listItemPanel3.setTitle("Most Selling Product");
        listItemPanel3.setLeading("25Kg");
        listItemPanel3.setSubTitle("Suger");
        
        listItemPanel2.setTitle("Lowest Selling Product");
        listItemPanel2.setLeading("200g");
        listItemPanel2.setSubTitle("Curry Powder");
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productSaleChartLabel = new javax.swing.JLabel();
        chart = new com.raven.chart.Chart();
        combo_SaleOrProfit = new javax.swing.JComboBox<>();
        listItemPanel2 = new components.ListItemPanel();
        listItemPanel3 = new components.ListItemPanel();
        jButton1 = new javax.swing.JButton();

        productSaleChartLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        productSaleChartLabel.setText("All Product All Sales");

        combo_SaleOrProfit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sales", "Profit" }));
        combo_SaleOrProfit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_SaleOrProfitItemStateChanged(evt);
            }
        });

        listItemPanel2.setLeading("2Kg");
        listItemPanel2.setSubTitle("Powder");
        listItemPanel2.setTitle("Lowest Selling Product");
        listItemPanel2.setVerifyInputWhenFocusTarget(false);

        listItemPanel3.setLeading("50Kg");
        listItemPanel3.setSubTitle("Suger");
        listItemPanel3.setTitle("Top Selling Product");

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Print Selling Report");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(productSaleChartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(listItemPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listItemPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                            .addComponent(combo_SaleOrProfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productSaleChartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(combo_SaleOrProfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listItemPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listItemPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(174, 174, 174))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combo_SaleOrProfitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_SaleOrProfitItemStateChanged
        // TODO add your handling code here:
//        randomize();
    }//GEN-LAST:event_combo_SaleOrProfitItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.chart.Chart chart;
    private javax.swing.JComboBox<String> combo_SaleOrProfit;
    private javax.swing.JButton jButton1;
    private components.ListItemPanel listItemPanel2;
    private components.ListItemPanel listItemPanel3;
    private javax.swing.JLabel productSaleChartLabel;
    // End of variables declaration//GEN-END:variables
}
