/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components.unitComboBox;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.SubCategory;
import models.Unit;
import services.UnitService;

/**
 *
 * @author vidur
 */
public class UnitComboBox extends javax.swing.JPanel {

    /**
     * Creates new form UnitComboBox
     */
    final UnitService service;
    List<Unit> units = new ArrayList<>();
    UnitComboBoxInterface unitBoxInterface;
    Unit selectedUnit;
    public UnitComboBox() {
        initComponents();
        service  = new UnitService();
        loadUnit();
    }
    
    private void loadUnit(){
        try {
            units.addAll(service.getAllUnits());
            DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
            comboBoxModel.removeAllElements();
            for (Unit unit : units) {
                comboBoxModel.addElement(unit.getUnit());
            }
            jComboBox1.setModel(comboBoxModel);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    
    public void onSelect(Unit unit){
        selectedUnit = unit;
       jComboBox1.setSelectedItem(unit.getUnit());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
