/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components.unitComboBox;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import dto.Category;
import dto.SubCategory;
import dto.Unit;
import services.UnitService;

/**
 *
 * @author vidur
 */
public class UnitComboBox extends javax.swing.JPanel {

    /**
     * Creates new form UnitComboBox
     */
    final UnitService service;
    List<Unit> units = new ArrayList<>();
    UnitComboBoxInterface unitBoxInterface;
    Unit selectedUnit;
    public UnitComboBox() {
        initComponents();
        service  = new UnitService();
        loadUnit();
    }
    
    public  Unit getSelectedItem(){
        String selectedUnitName = (String) jComboBox1.getSelectedItem();
            for (Unit unit : units) {
                if (unit.getUnit().equals(selectedUnitName)) {
                    selectedUnit = unit;
                    return unit;
                }
            }
        return null;
    }
    
    public void setSelectedItem(Unit unit){
        jComboBox1.setSelectedItem(unit.getUnit());
    }
    
    private void loadUnit(){
        try {
            units.addAll(service.getAllUnits());
            if(!units.isEmpty()){
                selectedUnit = units.get(0);
                if (unitBoxInterface != null) {
                        unitBoxInterface.onSelectUnit(units.get(0));
                    }
            }
            DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
            comboBoxModel.removeAllElements();
            for (Unit unit : units) {
                comboBoxModel.addElement(unit.getUnit());
            }
            jComboBox1.setModel(comboBoxModel);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    
    public void onSelect(Unit unit){
        selectedUnit = unit;
       jComboBox1.setSelectedItem(unit.getUnit());
    }
    public void setInterface(UnitComboBoxInterface face){
        this.unitBoxInterface = face;
    }
    
    public Unit getSelectedUnit(){
        return this.selectedUnit;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        String selectedUnitName = (String) jComboBox1.getSelectedItem();
            for (Unit unit : units) {
                if (unit.getUnit().equals(selectedUnitName)) {
                    selectedUnit = unit;
                    if (unitBoxInterface != null) {
                        unitBoxInterface.onSelectUnit(unit);
                    }
                    break;
                }
            }
    }//GEN-LAST:event_jComboBox1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
