/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

/**
 *
 * @author vidur
 */
public class ListItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListItemPanel
     */
    private String title = "title";
    private String leading = "leading";
    private String subTitle = "subTitle";
    
    public ListItemPanel() {
        initComponents();
        tf_title.setText(title);
        tf_leading.setText(leading);
        tf_subTitle.setText(subTitle);
         setOpaque(false);
    }
    
    public void setTitle(String title){
        this.title  = title;
        tf_title.setText(title);
        tf_leading.setText(leading);
        tf_subTitle.setText(subTitle);
        repaint();
    }
    
    public void setLeading(String leading){
        this.leading = leading;
        tf_title.setText(title);
        tf_leading.setText(leading);
        tf_subTitle.setText(subTitle);
                repaint();

    }
    public void setSubTitle(String subTitle){
        this.subTitle = subTitle;
        tf_title.setText(title);
        tf_leading.setText(leading);
        tf_subTitle.setText(subTitle);
                repaint();

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new components.RoundedPanel();
        tf_title = new javax.swing.JLabel();
        tf_leading = new javax.swing.JLabel();
        tf_subTitle = new javax.swing.JLabel();

        roundedPanel1.setBackground(new java.awt.Color(221, 231, 244));

        tf_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_title.setText("Title Text is Here");

        tf_leading.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tf_leading.setForeground(new java.awt.Color(255, 0, 0));
        tf_leading.setText("5Kg");

        tf_subTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_subTitle.setText("Suger");

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tf_title, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(tf_leading, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_subTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_title)
                .addGap(0, 0, 0)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_leading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_subTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.RoundedPanel roundedPanel1;
    private javax.swing.JLabel tf_leading;
    private javax.swing.JLabel tf_subTitle;
    private javax.swing.JLabel tf_title;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * @return the leading
     */
    public String getLeading() {
        return leading;
    }

    /**
     * @return the subTitle
     */
    public String getSubTitle() {
        return subTitle;
    }
}
