/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components.categoryComboBox;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.Category;
import models.SubCategory;
import services.SubCategoryService;

/**
 *
 * @author vidur
 */
public class SubCategoryComboBox extends javax.swing.JPanel {

    /**
     * Creates new form SubCategoryComboBox
     */
    final SubCategoryService service ;
    List<SubCategory> subcategories = new ArrayList<>();
    SubCategory selectedSubCategory;
    SubCategoryComboBoxInterface subCatBoxInterface;
    public SubCategoryComboBox() {
        initComponents();
        service = new SubCategoryService();
        loadCategory();
    }
    
     private void loadCategory() {
        try {
            subcategories.addAll(service.getAllSubCategories());
            DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
            comboBoxModel.removeAllElements();
            for (SubCategory category : subcategories) {
                comboBoxModel.addElement(category.getSubCategory());
            }
            jComboBox1.setModel(comboBoxModel);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

    }
     
     public void onSelect(SubCategory subcat){
         selectedSubCategory = subcat;
         jComboBox1.setSelectedItem(subcat.getSubCategory());
     }
     
     public void setCategoryComboBoxInterface(SubCategoryComboBoxInterface boxInterface){
        this.subCatBoxInterface = boxInterface;
    }
    
    public SubCategory getSelectedCategory(){
        return selectedSubCategory;
    }
    
    public void refresh(){
        loadCategory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jComboBox1)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
